{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Snyk Container",
          "properties": {
            "artifactsScanned": 46
          },
          "rules": [
            {
              "id": "SNYK-ALPINE318-BUSYBOX-6913411",
              "shortDescription": {
                "text": "Medium severity - Out-of-bounds Write vulnerability in busybox"
              },
              "fullDescription": {
                "text": "(CVE-2023-42366) busybox/busybox@1.36.1-r5"
              },
              "help": {
                "text": "",
                "markdown": "## NVD Description\n**_Note:_** _Versions mentioned in the description apply only to the upstream `busybox` package and not the `busybox` package as distributed by `Alpine`._\n_See `How to fix?` for `Alpine:3.18` relevant fixed versions and status._\n\nA heap-buffer-overflow was discovered in BusyBox v.1.36.1 in the next_token function at awk.c:1159.\n## Remediation\nUpgrade `Alpine:3.18` `busybox` to version 1.36.1-r6 or higher.\n## References\n- [https://bugs.busybox.net/show_bug.cgi?id=15874](https://bugs.busybox.net/show_bug.cgi?id=15874)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-787",
                  "apk"
                ],
                "cvssv3_baseScore": 5.5,
                "security-severity": "5.5"
              }
            },
            {
              "id": "SNYK-ALPINE318-BUSYBOX-7249236",
              "shortDescription": {
                "text": "Medium severity - Use After Free vulnerability in busybox"
              },
              "fullDescription": {
                "text": "(CVE-2023-42363) busybox/busybox@1.36.1-r5"
              },
              "help": {
                "text": "",
                "markdown": "## NVD Description\n**_Note:_** _Versions mentioned in the description apply only to the upstream `busybox` package and not the `busybox` package as distributed by `Alpine`._\n_See `How to fix?` for `Alpine:3.18` relevant fixed versions and status._\n\nA use-after-free vulnerability was discovered in xasprintf function in xfuncs_printf.c:344 in BusyBox v.1.36.1.\n## Remediation\nUpgrade `Alpine:3.18` `busybox` to version 1.36.1-r7 or higher.\n## References\n- [https://bugs.busybox.net/show_bug.cgi?id=15865](https://bugs.busybox.net/show_bug.cgi?id=15865)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-416",
                  "apk"
                ],
                "cvssv3_baseScore": 5.5,
                "security-severity": "5.5"
              }
            },
            {
              "id": "SNYK-ALPINE318-BUSYBOX-7249265",
              "shortDescription": {
                "text": "Medium severity - Use After Free vulnerability in busybox"
              },
              "fullDescription": {
                "text": "(CVE-2023-42364) busybox/busybox@1.36.1-r5"
              },
              "help": {
                "text": "",
                "markdown": "## NVD Description\n**_Note:_** _Versions mentioned in the description apply only to the upstream `busybox` package and not the `busybox` package as distributed by `Alpine`._\n_See `How to fix?` for `Alpine:3.18` relevant fixed versions and status._\n\nA use-after-free vulnerability in BusyBox v.1.36.1 allows attackers to cause a denial of service via a crafted awk pattern in the awk.c evaluate function.\n## Remediation\nUpgrade `Alpine:3.18` `busybox` to version 1.36.1-r7 or higher.\n## References\n- [https://bugs.busybox.net/show_bug.cgi?id=15868](https://bugs.busybox.net/show_bug.cgi?id=15868)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-416",
                  "apk"
                ],
                "cvssv3_baseScore": 5.5,
                "security-severity": "5.5"
              }
            },
            {
              "id": "SNYK-ALPINE318-BUSYBOX-7249419",
              "shortDescription": {
                "text": "Medium severity - Use After Free vulnerability in busybox"
              },
              "fullDescription": {
                "text": "(CVE-2023-42365) busybox/busybox@1.36.1-r5"
              },
              "help": {
                "text": "",
                "markdown": "## NVD Description\n**_Note:_** _Versions mentioned in the description apply only to the upstream `busybox` package and not the `busybox` package as distributed by `Alpine`._\n_See `How to fix?` for `Alpine:3.18` relevant fixed versions and status._\n\nA use-after-free vulnerability was discovered in BusyBox v.1.36.1 via a crafted awk pattern in the awk.c copyvar function.\n## Remediation\nUpgrade `Alpine:3.18` `busybox` to version 1.36.1-r7 or higher.\n## References\n- [https://bugs.busybox.net/show_bug.cgi?id=15871](https://bugs.busybox.net/show_bug.cgi?id=15871)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-416",
                  "apk"
                ],
                "cvssv3_baseScore": 5.5,
                "security-severity": "5.5"
              }
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "SNYK-ALPINE318-BUSYBOX-6913411",
          "level": "warning",
          "message": {
            "text": "This file introduces a vulnerable busybox package with a medium severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "certbot/certbot_v2.11.0/certbot"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "busybox@1.36.1-r5"
                }
              ]
            }
          ],
          "fixes": [
            {
              "description": {
                "text": "Upgrade to busybox/busybox@1.36.1-r6"
              },
              "artifactChanges": [
                {
                  "artifactLocation": {
                    "uri": "certbot/certbot_v2.11.0/certbot"
                  },
                  "replacements": [
                    {
                      "deletedRegion": {
                        "startLine": 1
                      },
                      "insertedContent": {
                        "text": "busybox/busybox@1.36.1-r6"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-ALPINE318-BUSYBOX-7249236",
          "level": "warning",
          "message": {
            "text": "This file introduces a vulnerable busybox package with a medium severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "certbot/certbot_v2.11.0/certbot"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "busybox@1.36.1-r5"
                }
              ]
            }
          ],
          "fixes": [
            {
              "description": {
                "text": "Upgrade to busybox/busybox@1.36.1-r7"
              },
              "artifactChanges": [
                {
                  "artifactLocation": {
                    "uri": "certbot/certbot_v2.11.0/certbot"
                  },
                  "replacements": [
                    {
                      "deletedRegion": {
                        "startLine": 1
                      },
                      "insertedContent": {
                        "text": "busybox/busybox@1.36.1-r7"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-ALPINE318-BUSYBOX-7249265",
          "level": "warning",
          "message": {
            "text": "This file introduces a vulnerable busybox package with a medium severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "certbot/certbot_v2.11.0/certbot"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "busybox@1.36.1-r5"
                }
              ]
            }
          ],
          "fixes": [
            {
              "description": {
                "text": "Upgrade to busybox/busybox@1.36.1-r7"
              },
              "artifactChanges": [
                {
                  "artifactLocation": {
                    "uri": "certbot/certbot_v2.11.0/certbot"
                  },
                  "replacements": [
                    {
                      "deletedRegion": {
                        "startLine": 1
                      },
                      "insertedContent": {
                        "text": "busybox/busybox@1.36.1-r7"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-ALPINE318-BUSYBOX-7249419",
          "level": "warning",
          "message": {
            "text": "This file introduces a vulnerable busybox package with a medium severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "certbot/certbot_v2.11.0/certbot"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "busybox@1.36.1-r5"
                }
              ]
            }
          ],
          "fixes": [
            {
              "description": {
                "text": "Upgrade to busybox/busybox@1.36.1-r7"
              },
              "artifactChanges": [
                {
                  "artifactLocation": {
                    "uri": "certbot/certbot_v2.11.0/certbot"
                  },
                  "replacements": [
                    {
                      "deletedRegion": {
                        "startLine": 1
                      },
                      "insertedContent": {
                        "text": "busybox/busybox@1.36.1-r7"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "tool": {
        "driver": {
          "name": "Snyk Container",
          "properties": {
            "artifactsScanned": 18
          },
          "rules": [
            {
              "id": "SNYK-PYTHON-CONFIGOBJ-3252494",
              "shortDescription": {
                "text": "Low severity - Regular Expression Denial of Service (ReDoS) vulnerability in configobj"
              },
              "fullDescription": {
                "text": "(CVE-2023-26112) configobj@5.0.8"
              },
              "help": {
                "text": "",
                "markdown": "## Overview\n[configobj](https://pypi.org/project/configobj) is a Config file reading, writing and validation.\n\nAffected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) via the `validate` function, using `(.+?)\\((.*)\\)`.\r\n\r\n**Note:** This is only exploitable in the case of a developer, putting the offending value in a server side configuration file.\r\n\r\n## PoC\r\n```py\r\nfrom configobj.validate import Validator\r\nvalue = \"aaa\"\r\ni = 10\r\nattack = '\\x00'*16510*i + ')' + '('*16510*i\r\nvtor = Validator()\r\nnewval1 = vtor.check(attack, value)\r\n```\n\n## Details\n\nDenial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its original and legitimate users. There are many types of DoS attacks, ranging from trying to clog the network pipes to the system by generating a large volume of traffic from many machines (a Distributed Denial of Service - DDoS - attack) to sending crafted requests that cause a system to crash or take a disproportional amount of time to process.\n\nThe Regular expression Denial of Service (ReDoS) is a type of Denial of Service attack. Regular expressions are incredibly powerful, but they aren't very intuitive and can ultimately end up making it easy for attackers to take your site down.\n\nLet’s take the following regular expression as an example:\n```js\nregex = /A(B|C+)+D/\n```\n\nThis regular expression accomplishes the following:\n- `A` The string must start with the letter 'A'\n- `(B|C+)+` The string must then follow the letter A with either the letter 'B' or some number of occurrences of the letter 'C' (the `+` matches one or more times). The `+` at the end of this section states that we can look for one or more matches of this section.\n- `D` Finally, we ensure this section of the string ends with a 'D'\n\nThe expression would match inputs such as `ABBD`, `ABCCCCD`, `ABCBCCCD` and `ACCCCCD`\n\nIt most cases, it doesn't take very long for a regex engine to find a match:\n\n```bash\n$ time node -e '/A(B|C+)+D/.test(\"ACCCCCCCCCCCCCCCCCCCCCCCCCCCCD\")'\n0.04s user 0.01s system 95% cpu 0.052 total\n\n$ time node -e '/A(B|C+)+D/.test(\"ACCCCCCCCCCCCCCCCCCCCCCCCCCCCX\")'\n1.79s user 0.02s system 99% cpu 1.812 total\n```\n\nThe entire process of testing it against a 30 characters long string takes around ~52ms. But when given an invalid string, it takes nearly two seconds to complete the test, over ten times as long as it took to test a valid string. The dramatic difference is due to the way regular expressions get evaluated.\n\nMost Regex engines will work very similarly (with minor differences). The engine will match the first possible way to accept the current character and proceed to the next one. If it then fails to match the next one, it will backtrack and see if there was another way to digest the previous character. If it goes too far down the rabbit hole only to find out the string doesn’t match in the end, and if many characters have multiple valid regex paths, the number of backtracking steps can become very large, resulting in what is known as _catastrophic backtracking_.\n\nLet's look at how our expression runs into this problem, using a shorter string: \"ACCCX\". While it seems fairly straightforward, there are still four different ways that the engine could match those three C's:\n1. CCC\n2. CC+C\n3. C+CC\n4. C+C+C.\n\nThe engine has to try each of those combinations to see if any of them potentially match against the expression. When you combine that with the other steps the engine must take, we can use [RegEx 101 debugger](https://regex101.com/debugger) to see the engine has to take a total of 38 steps before it can determine the string doesn't match.\n\nFrom there, the number of steps the engine must use to validate a string just continues to grow.\n\n| String | Number of C's | Number of steps |\n| -------|-------------:| -----:|\n| ACCCX | 3 | 38\n| ACCCCX | 4 | 71\n| ACCCCCX | 5 | 136\n| ACCCCCCCCCCCCCCX | 14 | 65,553\n\n\nBy the time the string includes 14 C's, the engine has to take over 65,000 steps just to see if the string is valid. These extreme situations can cause them to work very slowly (exponentially related to input size, as shown above), allowing an attacker to exploit this and can cause the service to excessively consume CPU, resulting in a Denial of Service.\n\n## Remediation\nThere is no fixed version for `configobj`.\n\n## References\n- [GitHub Issue](https://github.com/DiffSK/configobj/issues/232)\n- [GitHub PR](https://github.com/DiffSK/configobj/pull/236)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-1333",
                  "pip"
                ],
                "cvssv3_baseScore": 3.7,
                "security-severity": "3.7"
              }
            },
            {
              "id": "SNYK-PYTHON-CRYPTOGRAPHY-6913422",
              "shortDescription": {
                "text": "Low severity - Uncontrolled Resource Consumption vulnerability in cryptography"
              },
              "fullDescription": {
                "text": "(CVE-2024-4603) cryptography@42.0.7"
              },
              "help": {
                "text": "",
                "markdown": "## Overview\n\nAffected versions of this package are vulnerable to Uncontrolled Resource Consumption due to improper user input validation in the `EVP_PKEY_param_check` or `EVP_PKEY_public_check` functions. An attacker can cause a denial of service by supplying excessively long DSA keys or parameters obtained from an untrusted source.\r\n\r\n**Note:**\r\n\r\nOpenSSL does not call these functions on untrusted DSA keys, so only applications that directly call these functions may be vulnerable.\r\n\r\nAlso vulnerable are the OpenSSL `pkey` and `pkeyparam` command line applications when using the \"-check\" option.\n## Remediation\nA fix was pushed into the `master` branch but not yet published.\n## References\n- [GitHub Commit](https://github.com/openssl/openssl/commit/85ccbab216da245cf9a6503dd327072f21950d9b)\n- [GitHub Commit 3.0](https://github.com/openssl/openssl/commit/3559e868e58005d15c6013a0c1fd832e51c73397)\n- [GitHub Commit 3.1](https://github.com/openssl/openssl/commit/9c39b3858091c152f52513c066ff2c5a47969f0d)\n- [GitHub Commit 3.2](https://github.com/openssl/openssl/commit/da343d0605c826ef197aceedc67e8e04f065f740)\n- [GitHub Commit 3.3](https://github.com/openssl/openssl/commit/53ea06486d296b890d565fb971b2764fcd826e7e)\n- [GitHub Commit cryptography](https://github.com/pyca/cryptography/commit/38852224f455af1915a628542b930ad11d2a884c)\n- [GitHub PR](https://github.com/openssl/openssl/pull/24346)\n- [OpenSSL advisory](https://www.openssl.org/news/secadv/20240516.txt)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-400",
                  "pip"
                ],
                "cvssv3_baseScore": 3.7,
                "security-severity": "3.7"
              }
            },
            {
              "id": "SNYK-PYTHON-CRYPTOGRAPHY-7161587",
              "shortDescription": {
                "text": "High severity - Use After Free vulnerability in cryptography"
              },
              "fullDescription": {
                "text": "(CVE-2024-4741) cryptography@42.0.7"
              },
              "help": {
                "text": "",
                "markdown": "## Overview\n\nAffected versions of this package are vulnerable to Use After Free via the `SSL_free_buffers` function. An attacker can execute arbitrary code, corrupt valid data or cause a crash by exploiting the freed memory area.\r\n\r\nThe `SSL_free_buffers` function is used to free the internal OpenSSL buffer used when processing an incoming record from the network. The call is only expected to succeed if the buffer is not currently in use. However, two scenarios have been identified where the buffer is freed even when still in use.\r\n\r\n1) The first scenario occurs where a record header has been received from the network and processed by OpenSSL, but the full record body has not yet arrived. In this case calling `SSL_free_buffers` will succeed even though a record has only been partially processed and the buffer is still in use.\r\n\r\n2) The second scenario occurs where a full record containing application data has been received and processed by OpenSSL but the application has only read part of this data. Again a call to `SSL_free_buffers` will succeed even though the buffer is still in use.\r\n\r\nWhile these scenarios could occur accidentally during normal operation a malicious attacker could attempt to engineer a situation where this occurs.\r\n\r\n**Note:**\r\n\r\nThe FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.\n## Remediation\nUpgrade `cryptography` to version 42.0.8 or higher.\n## References\n- [GitHub Commit](https://github.com/openssl/openssl/commit/704f725b96aa373ee45ecfb23f6abfe8be8d9177)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/b3f0eb0a295f58f16ba43ba99dad70d4ee5c437d)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/c88c3de51020c37e8706bf7a682a162593053aac)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/e5093133c35ca82874ad83697af76f4b0f7e3bd8)\n- [GitHub Commit](https://github.com/pyca/cryptography/commit/761ef4b955697c63e83734096f672224224082e1)\n- [OpenSSL Advisory](https://www.openssl.org/news/secadv/20240528.txt)\n- [RedHat Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2283757)\n"
              },
              "defaultConfiguration": {
                "level": "error"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-416",
                  "pip"
                ],
                "cvssv3_baseScore": 8.1,
                "security-severity": "8.1"
              }
            },
            {
              "id": "SNYK-PYTHON-PYOPENSSL-6149520",
              "shortDescription": {
                "text": "Medium severity - Use of a Broken or Risky Cryptographic Algorithm vulnerability in pyopenssl"
              },
              "fullDescription": {
                "text": "(CVE-2023-6129) pyopenssl@24.1.0"
              },
              "help": {
                "text": "",
                "markdown": "## Overview\n\nAffected versions of this package are vulnerable to Use of a Broken or Risky Cryptographic Algorithm due to an issue in the `POLY1305` MAC implementation on PowerPC CPUs. An attacker can corrupt the application state and cause incorrect calculations or potential denial of service by influencing the use of the `POLY1305` MAC algorithm.\r\n\r\n**Note:**\r\n\r\nThis is only exploitable if the attacker has the ability to affect the algorithm's usage and the application relies on non-volatile XMM registers.\n## Remediation\nThere is no fixed version for `pyOpenSSL`.\n\n## References\n- [GitHub Commit](https://github.com/openssl/openssl/commit/050d26383d4e264966fb83428e72d5d48f402d35)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/5b139f95c9a47a55a0c54100f3837b1eee942b04)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/f3fc5808fe9ff74042d639839610d03b8fdcc015)\n- [GitHub Commit](https://github.com/pyca/cryptography/commit/89d0d56fb104ac4e0e6db63d78fc22b8c53d27e9)\n- [OpenSSL Advisory](https://www.openssl.org/news/secadv/20240109.txt)\n- [RedHat Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2257571)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-328",
                  "pip"
                ],
                "cvssv3_baseScore": 5.9,
                "security-severity": "5.9"
              }
            },
            {
              "id": "SNYK-PYTHON-PYOPENSSL-6157250",
              "shortDescription": {
                "text": "Medium severity - Resource Exhaustion vulnerability in pyopenssl"
              },
              "fullDescription": {
                "text": "(CVE-2023-6237) pyopenssl@24.1.0"
              },
              "help": {
                "text": "",
                "markdown": "## Overview\n\nAffected versions of this package are vulnerable to Resource Exhaustion via the `EVP_PKEY_public_check` function. When the function is called in RSA public keys, a computation is done to confirm that the RSA modulus, n, is composite. For valid RSA keys, n is a product of two or more large primes and this computation completes quickly. However, if n is a large prime, this computation takes a long time. An attacker can cause a denial of service by supplying a specially crafted RSA key that triggers extensive computation.\n\n## Details\n\nDenial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its intended and legitimate users.\n\nUnlike other vulnerabilities, DoS attacks usually do not aim at breaching security. Rather, they are focused on making websites and services unavailable to genuine users resulting in downtime.\n\nOne popular Denial of Service vulnerability is DDoS (a Distributed Denial of Service), an attack that attempts to clog network pipes to the system by generating a large volume of traffic from many machines.\n\nWhen it comes to open source libraries, DoS vulnerabilities allow attackers to trigger such a crash or crippling of the service by using a flaw either in the application code or from the use of open source libraries.\n\nTwo common types of DoS vulnerabilities:\n\n* High CPU/Memory Consumption- An attacker sending crafted requests that could cause the system to take a disproportionate amount of time to process. For example, [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).\n\n* Crash - An attacker sending crafted requests that could cause the system to crash. For Example,  [npm `ws` package](https://snyk.io/vuln/npm:ws:20171108)\n\n## Remediation\nThere is no fixed version for `pyopenssl`.\n\n## References\n- [GitHub Commit](https://github.com/openssl/openssl/commit/0b0f7abfb37350794a4b8960fafc292cd5d1b84d)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/18c02492138d1eb8b6548cb26e7b625fb2414a2a)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/a830f551557d3d66a84bbb18a5b889c640c36294)\n- [GitHub Commit](https://github.com/pyca/cryptography/commit/4b5be7b0032ade70e09a43f9d857708e36170bbc)\n- [OpenSSL Advisory](https://www.openssl.org/news/secadv/20240115.txt)\n- [RedHat Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2258502)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-400",
                  "pip"
                ],
                "cvssv3_baseScore": 5.9,
                "security-severity": "5.9"
              }
            },
            {
              "id": "SNYK-PYTHON-PYOPENSSL-6592766",
              "shortDescription": {
                "text": "Low severity - Uncontrolled Resource Consumption ('Resource Exhaustion') vulnerability in pyopenssl"
              },
              "fullDescription": {
                "text": "(CVE-2024-2511) pyopenssl@24.1.0"
              },
              "help": {
                "text": "",
                "markdown": "## Overview\n\nAffected versions of this package are vulnerable to Uncontrolled Resource Consumption ('Resource Exhaustion') due to the session cache entering an incorrect state and failing to flush properly as it fills, leading to uncontrolled memory consumption. This condition is triggered under certain server configurations when processing TLSv1.3 sessions. Specifically, this occurs if the non-default `SSL_OP_NO_TICKET` option is enabled, but not if early_data support is configured along with the default anti-replay protection. A malicious client could deliberately create this scenario to force a service disruption. It may also occur accidentally in normal operation.\r\n\r\n**Note:**\r\n\r\nThis issue is only exploitable if the server supports TLSv1.3 and is configured with the `SSL_OP_NO_TICKET` option enabled.\n## Remediation\nThere is no fixed version for `pyOpenSSL`.\n\n## References\n- [GitHub Commit](https://github.com/openssl/openssl/commit/21df7f04f6c4a560b4de56d10e1e58958c7e566d)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/4a3e8f08306c64366318e26162ae0a0eb7b1a006)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/7984fa683e9dfac0cad50ef2a9d5a13330222044)\n- [GitHub Commit](https://github.com/pyca/cryptography/commit/42192fab0a96b484089021148ed1eaa12053f7ed)\n- [RedHat Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2274020)\n- [Vulnerability Advisory](https://www.openssl.org/news/secadv/20240408.txt)\n"
              },
              "defaultConfiguration": {
                "level": "warning"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-400",
                  "pip"
                ],
                "cvssv3_baseScore": 3.7,
                "security-severity": "3.7"
              }
            },
            {
              "id": "SNYK-PYTHON-PYOPENSSL-7161590",
              "shortDescription": {
                "text": "High severity - Use After Free vulnerability in pyopenssl"
              },
              "fullDescription": {
                "text": "(CVE-2024-4741) pyopenssl@24.1.0"
              },
              "help": {
                "text": "",
                "markdown": "## Overview\n\nAffected versions of this package are vulnerable to Use After Free via the `SSL_free_buffers` function. An attacker can execute arbitrary code, corrupt valid data or cause a crash by exploiting the freed memory area.\r\n\r\nThe `SSL_free_buffers` function is used to free the internal OpenSSL buffer used when processing an incoming record from the network. The call is only expected to succeed if the buffer is not currently in use. However, two scenarios have been identified where the buffer is freed even when still in use.\r\n\r\n1) The first scenario occurs where a record header has been received from the network and processed by OpenSSL, but the full record body has not yet arrived. In this case calling `SSL_free_buffers` will succeed even though a record has only been partially processed and the buffer is still in use.\r\n\r\n2) The second scenario occurs where a full record containing application data has been received and processed by OpenSSL but the application has only read part of this data. Again a call to `SSL_free_buffers` will succeed even though the buffer is still in use.\r\n\r\nWhile these scenarios could occur accidentally during normal operation a malicious attacker could attempt to engineer a situation where this occurs.\r\n\r\n**Note:**\r\n\r\nThe FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.\n## Remediation\nThere is no fixed version for `pyOpenSSL`.\n\n## References\n- [GitHub Commit](https://github.com/openssl/openssl/commit/704f725b96aa373ee45ecfb23f6abfe8be8d9177)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/b3f0eb0a295f58f16ba43ba99dad70d4ee5c437d)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/c88c3de51020c37e8706bf7a682a162593053aac)\n- [GitHub Commit](https://github.com/openssl/openssl/commit/e5093133c35ca82874ad83697af76f4b0f7e3bd8)\n- [GitHub Commit](https://github.com/pyca/cryptography/commit/761ef4b955697c63e83734096f672224224082e1)\n- [OpenSSL Advisory](https://www.openssl.org/news/secadv/20240528.txt)\n- [RedHat Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2283757)\n"
              },
              "defaultConfiguration": {
                "level": "error"
              },
              "properties": {
                "tags": [
                  "security",
                  "CWE-416",
                  "pip"
                ],
                "cvssv3_baseScore": 8.1,
                "security-severity": "8.1"
              }
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "SNYK-PYTHON-CONFIGOBJ-3252494",
          "level": "note",
          "message": {
            "text": "This file introduces a vulnerable configobj package with a low severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/opt/certbot/tools/requirements.txt"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "configobj@5.0.8"
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-PYTHON-CRYPTOGRAPHY-6913422",
          "level": "note",
          "message": {
            "text": "This file introduces a vulnerable cryptography package with a low severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/opt/certbot/tools/requirements.txt"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "cryptography@42.0.7"
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-PYTHON-CRYPTOGRAPHY-7161587",
          "level": "error",
          "message": {
            "text": "This file introduces a vulnerable cryptography package with a high severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/opt/certbot/tools/requirements.txt"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "cryptography@42.0.7"
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-PYTHON-PYOPENSSL-6149520",
          "level": "warning",
          "message": {
            "text": "This file introduces a vulnerable pyopenssl package with a medium severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/opt/certbot/tools/requirements.txt"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "pyopenssl@24.1.0"
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-PYTHON-PYOPENSSL-6157250",
          "level": "warning",
          "message": {
            "text": "This file introduces a vulnerable pyopenssl package with a medium severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/opt/certbot/tools/requirements.txt"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "pyopenssl@24.1.0"
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-PYTHON-PYOPENSSL-6592766",
          "level": "note",
          "message": {
            "text": "This file introduces a vulnerable pyopenssl package with a low severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/opt/certbot/tools/requirements.txt"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "pyopenssl@24.1.0"
                }
              ]
            }
          ]
        },
        {
          "ruleId": "SNYK-PYTHON-PYOPENSSL-7161590",
          "level": "error",
          "message": {
            "text": "This file introduces a vulnerable pyopenssl package with a high severity vulnerability."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/opt/certbot/tools/requirements.txt"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "pyopenssl@24.1.0"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
