fluent/fluent-bit:windows-2019-3.0.6 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test fluent/fluent-bit:windows-2019-3.0.6 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_fluent=fluent-bit:windows-2019-3.0.6_2024-06-15_19:24:46.json] execution failed: exit status 2
Output: Operating system is not supported
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluent/fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_fluent=fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig_2024-06-15_19:28:28.json fluent/fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig] execution failed: exit status 1
Output: 2024-06-15T19:28:29Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:28:29Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:9ffef546a50e30a497ba11eb77cae27aacd23c964465c2cb93b73d4aa7b7d7cc): unable to get uncompressed layer sha256:9ffef546a50e30a497ba11eb77cae27aacd23c964465c2cb93b73d4aa7b7d7cc: failed to get the layer (sha256:9ffef546a50e30a497ba11eb77cae27aacd23c964465c2cb93b73d4aa7b7d7cc): unable to populate: unable to open: failed to copy the image: image "fluent/fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig": not found
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_fluent=fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig_2024-06-15_19:28:28.json fluent/fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig] execution failed: exit status 1
Output: [31mfailed to catalog: errors occurred attempting to resolve 'fluent/fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: fluent/fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:9ffef546a50e30a497ba11eb77cae27aacd23c964465c2cb93b73d4aa7b7d7cc" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_fluent=fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig_2024-06-15_19:28:28.json fluent/fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/d77e08660d133c5764ea79ef90e8310b082279b6d6b41e438fbeceb7bb5470d3/34ceed8b-dbcc-46e7-a78a-7e73cee9b153', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/d77e08660d133c5764ea79ef90e8310b082279b6d6b41e438fbeceb7bb5470d3/34ceed8b-dbcc-46e7-a78a-7e73cee9b153: is a directory
read /tmp/docker-scout/sha256/d77e08660d133c5764ea79ef90e8310b082279b6d6b41e438fbeceb7bb5470d3/34ceed8b-dbcc-46e7-a78a-7e73cee9b153: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/d77e08660d133c5764ea79ef90e8310b082279b6d6b41e438fbeceb7bb5470d3/34ceed8b-dbcc-46e7-a78a-7e73cee9b153: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/d77e08660d133c5764ea79ef90e8310b082279b6d6b41e438fbeceb7bb5470d3/34ceed8b-dbcc-46e7-a78a-7e73cee9b153": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/d77e08660d133c5764ea79ef90e8310b082279b6d6b41e438fbeceb7bb5470d3/34ceed8b-dbcc-46e7-a78a-7e73cee9b153/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/d77e08660d133c5764ea79ef90e8310b082279b6d6b41e438fbeceb7bb5470d3/34ceed8b-dbcc-46e7-a78a-7e73cee9b153 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test fluent/fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_fluent=fluent-bit:sha256-492a03f1df699d25e3557e7b2f93a02f5407f1085a8bb2162d1d6b6285ef020d.sig_2024-06-15_19:28:28.json] execution failed: exit status 2
Output: Invalid OCI archive

fluent/fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_fluent=fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig_2024-06-15_19:28:38.json fluent/fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig] execution failed: exit status 1
Output: 2024-06-15T19:28:39Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:28:39Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:f2bf7f3810d6f8de5b47310735e5c32863e6260315f74989822b5f67e140918c): unable to get uncompressed layer sha256:f2bf7f3810d6f8de5b47310735e5c32863e6260315f74989822b5f67e140918c: failed to get the layer (sha256:f2bf7f3810d6f8de5b47310735e5c32863e6260315f74989822b5f67e140918c): unable to populate: unable to open: failed to copy the image: image "fluent/fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig": not found
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_fluent=fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig_2024-06-15_19:28:38.json fluent/fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig] execution failed: exit status 1
Output: [31mfailed to catalog: errors occurred attempting to resolve 'fluent/fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: fluent/fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:f2bf7f3810d6f8de5b47310735e5c32863e6260315f74989822b5f67e140918c" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_fluent=fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig_2024-06-15_19:28:38.json fluent/fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/4973282eb9b4946fc5fb74b6581d5792c9dcc46f671e7ba5d959352566d8adc1/abc8bb7c-de5c-4a44-8972-3f27a6970b12', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/4973282eb9b4946fc5fb74b6581d5792c9dcc46f671e7ba5d959352566d8adc1/abc8bb7c-de5c-4a44-8972-3f27a6970b12: is a directory
read /tmp/docker-scout/sha256/4973282eb9b4946fc5fb74b6581d5792c9dcc46f671e7ba5d959352566d8adc1/abc8bb7c-de5c-4a44-8972-3f27a6970b12: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/4973282eb9b4946fc5fb74b6581d5792c9dcc46f671e7ba5d959352566d8adc1/abc8bb7c-de5c-4a44-8972-3f27a6970b12: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/4973282eb9b4946fc5fb74b6581d5792c9dcc46f671e7ba5d959352566d8adc1/abc8bb7c-de5c-4a44-8972-3f27a6970b12": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/4973282eb9b4946fc5fb74b6581d5792c9dcc46f671e7ba5d959352566d8adc1/abc8bb7c-de5c-4a44-8972-3f27a6970b12/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/4973282eb9b4946fc5fb74b6581d5792c9dcc46f671e7ba5d959352566d8adc1/abc8bb7c-de5c-4a44-8972-3f27a6970b12 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test fluent/fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_fluent=fluent-bit:sha256-d6c1eec4de8f3c691871e2f2e1f4ee55659a9e1a63dfd57e58d1e16ff65686de.sig_2024-06-15_19:28:38.json] execution failed: exit status 2
Output: Invalid OCI archive

fluent/fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_fluent=fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig_2024-06-15_19:28:48.json fluent/fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig] execution failed: exit status 1
Output: 2024-06-15T19:28:49Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:28:49Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:d28a34d34ef2f7474c0e6fcb15eed434dd0bfbd72ab2824acf7b7a21908d62d7): unable to get uncompressed layer sha256:d28a34d34ef2f7474c0e6fcb15eed434dd0bfbd72ab2824acf7b7a21908d62d7: failed to get the layer (sha256:d28a34d34ef2f7474c0e6fcb15eed434dd0bfbd72ab2824acf7b7a21908d62d7): unable to populate: unable to open: failed to copy the image: image "fluent/fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig": not found
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_fluent=fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig_2024-06-15_19:28:48.json fluent/fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig] execution failed: exit status 1
Output: [31mfailed to catalog: errors occurred attempting to resolve 'fluent/fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: fluent/fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:d28a34d34ef2f7474c0e6fcb15eed434dd0bfbd72ab2824acf7b7a21908d62d7" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_fluent=fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig_2024-06-15_19:28:48.json fluent/fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/1688c4a1f8062c152bb02efa9680380d02070906de15836c3f1b98eac7f6154a/7ba679c2-9682-4688-9bb5-7dd23fc22996', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/1688c4a1f8062c152bb02efa9680380d02070906de15836c3f1b98eac7f6154a/7ba679c2-9682-4688-9bb5-7dd23fc22996: is a directory
read /tmp/docker-scout/sha256/1688c4a1f8062c152bb02efa9680380d02070906de15836c3f1b98eac7f6154a/7ba679c2-9682-4688-9bb5-7dd23fc22996: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/1688c4a1f8062c152bb02efa9680380d02070906de15836c3f1b98eac7f6154a/7ba679c2-9682-4688-9bb5-7dd23fc22996: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/1688c4a1f8062c152bb02efa9680380d02070906de15836c3f1b98eac7f6154a/7ba679c2-9682-4688-9bb5-7dd23fc22996": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/1688c4a1f8062c152bb02efa9680380d02070906de15836c3f1b98eac7f6154a/7ba679c2-9682-4688-9bb5-7dd23fc22996/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/1688c4a1f8062c152bb02efa9680380d02070906de15836c3f1b98eac7f6154a/7ba679c2-9682-4688-9bb5-7dd23fc22996 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test fluent/fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_fluent=fluent-bit:sha256-156c67fc56d4fff1354eea382f264b2296e485932d4c3e7c1e4d08c41446c9d9.sig_2024-06-15_19:28:48.json] execution failed: exit status 2
Output: Invalid OCI archive

fluent/fluent-bit:latest-debug ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
istio/pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig_2024-06-15_19:31:52.json istio/pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig] execution failed: exit status 1
Output: 2024-06-15T19:31:53Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:31:54Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:31c0dd3e137c8888d1bd3c6f5f58be12ec62860e6d39af81ef34a7360e0d233f): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig_2024-06-15_19:31:52.json istio/pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig] execution failed: exit status 1
Output: time="2024-06-15T19:31:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:31c0dd3e137c8888d1bd3c6f5f58be12ec62860e6d39af81ef34a7360e0d233f" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=243
time="2024-06-15T19:31:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:31:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:31:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:31c0dd3e137c8888d1bd3c6f5f58be12ec62860e6d39af81ef34a7360e0d233f" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig_2024-06-15_19:31:52.json istio/pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/b6f0d41bca5041d4a3e72721e4e04c5a2820acc6af34f9a531d0ac98db111790/8068d2a7-545b-4c5d-9650-4659d41146a3', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/b6f0d41bca5041d4a3e72721e4e04c5a2820acc6af34f9a531d0ac98db111790/8068d2a7-545b-4c5d-9650-4659d41146a3: is a directory
read /tmp/docker-scout/sha256/b6f0d41bca5041d4a3e72721e4e04c5a2820acc6af34f9a531d0ac98db111790/8068d2a7-545b-4c5d-9650-4659d41146a3: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/b6f0d41bca5041d4a3e72721e4e04c5a2820acc6af34f9a531d0ac98db111790/8068d2a7-545b-4c5d-9650-4659d41146a3: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/b6f0d41bca5041d4a3e72721e4e04c5a2820acc6af34f9a531d0ac98db111790/8068d2a7-545b-4c5d-9650-4659d41146a3": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/b6f0d41bca5041d4a3e72721e4e04c5a2820acc6af34f9a531d0ac98db111790/8068d2a7-545b-4c5d-9650-4659d41146a3/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/b6f0d41bca5041d4a3e72721e4e04c5a2820acc6af34f9a531d0ac98db111790/8068d2a7-545b-4c5d-9650-4659d41146a3 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=pilot:sha256-6563b13755f375a96f32e8182fc3986c3e9be6870b04e25441fb9aa79eae2119.sig_2024-06-15_19:31:52.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig_2024-06-15_19:32:02.json istio/pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig] execution failed: exit status 1
Output: 2024-06-15T19:32:03Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:32:05Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:7f787e06433b7ec536cf8dd1e38f9345b1873b59c22796fd1abece9e352b5087): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig_2024-06-15_19:32:02.json istio/pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig] execution failed: exit status 1
Output: time="2024-06-15T19:32:04Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:7f787e06433b7ec536cf8dd1e38f9345b1873b59c22796fd1abece9e352b5087" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=243
time="2024-06-15T19:32:04Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:04Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:04Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:04Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:04Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:05Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:7f787e06433b7ec536cf8dd1e38f9345b1873b59c22796fd1abece9e352b5087" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig_2024-06-15_19:32:02.json istio/pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/7cec93dd14b642639fb1dbee9b96bf05358293d61cbd53a1ef05b52cab165760/6844bd27-7667-479d-bf5a-2127df2a81c2', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/7cec93dd14b642639fb1dbee9b96bf05358293d61cbd53a1ef05b52cab165760/6844bd27-7667-479d-bf5a-2127df2a81c2: is a directory
read /tmp/docker-scout/sha256/7cec93dd14b642639fb1dbee9b96bf05358293d61cbd53a1ef05b52cab165760/6844bd27-7667-479d-bf5a-2127df2a81c2: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/7cec93dd14b642639fb1dbee9b96bf05358293d61cbd53a1ef05b52cab165760/6844bd27-7667-479d-bf5a-2127df2a81c2: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/7cec93dd14b642639fb1dbee9b96bf05358293d61cbd53a1ef05b52cab165760/6844bd27-7667-479d-bf5a-2127df2a81c2": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/7cec93dd14b642639fb1dbee9b96bf05358293d61cbd53a1ef05b52cab165760/6844bd27-7667-479d-bf5a-2127df2a81c2/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/7cec93dd14b642639fb1dbee9b96bf05358293d61cbd53a1ef05b52cab165760/6844bd27-7667-479d-bf5a-2127df2a81c2 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=pilot:sha256-f47bd42b307f673f7ba4a94270d4369ebafa33b156af57ad3e6d0b469b7a280a.sig_2024-06-15_19:32:02.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig_2024-06-15_19:32:12.json istio/pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig] execution failed: exit status 1
Output: 2024-06-15T19:32:13Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:32:15Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:48beb5606c8c64b15117be824c8c42cff49f3ddebf894083a18cafa8040e527f): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig_2024-06-15_19:32:12.json istio/pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig] execution failed: exit status 1
Output: time="2024-06-15T19:32:14Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:48beb5606c8c64b15117be824c8c42cff49f3ddebf894083a18cafa8040e527f" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=243
time="2024-06-15T19:32:14Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:14Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:14Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:15Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:15Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:15Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:15Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:15Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:15Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:15Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:48beb5606c8c64b15117be824c8c42cff49f3ddebf894083a18cafa8040e527f" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig_2024-06-15_19:32:12.json istio/pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/678bb59c356f3127cff5b7f5b3ba83b546e420986c6e7ff0e618f534b4a8d680/f600d181-7d65-468c-928c-177d8d5fc15d', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/678bb59c356f3127cff5b7f5b3ba83b546e420986c6e7ff0e618f534b4a8d680/f600d181-7d65-468c-928c-177d8d5fc15d: is a directory
read /tmp/docker-scout/sha256/678bb59c356f3127cff5b7f5b3ba83b546e420986c6e7ff0e618f534b4a8d680/f600d181-7d65-468c-928c-177d8d5fc15d: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/678bb59c356f3127cff5b7f5b3ba83b546e420986c6e7ff0e618f534b4a8d680/f600d181-7d65-468c-928c-177d8d5fc15d: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/678bb59c356f3127cff5b7f5b3ba83b546e420986c6e7ff0e618f534b4a8d680/f600d181-7d65-468c-928c-177d8d5fc15d": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/678bb59c356f3127cff5b7f5b3ba83b546e420986c6e7ff0e618f534b4a8d680/f600d181-7d65-468c-928c-177d8d5fc15d/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/678bb59c356f3127cff5b7f5b3ba83b546e420986c6e7ff0e618f534b4a8d680/f600d181-7d65-468c-928c-177d8d5fc15d Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=pilot:sha256-8faf2dd73595841e775b8fdd741be9ad1af2a147c1afc5abc61a1282536cb8c3.sig_2024-06-15_19:32:12.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/pilot:1.21.3-distroless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
istio/pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig_2024-06-15_19:32:34.json istio/pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig] execution failed: exit status 1
Output: 2024-06-15T19:32:35Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:32:36Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:0eea16ad92833b0f0efed89bcec8cca4dfd8724aa2b7c5a6bce784dabf0bde59): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig_2024-06-15_19:32:34.json istio/pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig] execution failed: exit status 1
Output: time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:0eea16ad92833b0f0efed89bcec8cca4dfd8724aa2b7c5a6bce784dabf0bde59" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=243
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:0eea16ad92833b0f0efed89bcec8cca4dfd8724aa2b7c5a6bce784dabf0bde59" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=243
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:36Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:37Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:37Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:37Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:0eea16ad92833b0f0efed89bcec8cca4dfd8724aa2b7c5a6bce784dabf0bde59" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig_2024-06-15_19:32:34.json istio/pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/2f7dfc55ecf5537d5a3969d370cedba388e8eb359d415c33cf2f2265cd5422e4/919966b4-b36b-4bc4-9a46-e817c9e5d3a1', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/2f7dfc55ecf5537d5a3969d370cedba388e8eb359d415c33cf2f2265cd5422e4/919966b4-b36b-4bc4-9a46-e817c9e5d3a1: is a directory
read /tmp/docker-scout/sha256/2f7dfc55ecf5537d5a3969d370cedba388e8eb359d415c33cf2f2265cd5422e4/919966b4-b36b-4bc4-9a46-e817c9e5d3a1: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/2f7dfc55ecf5537d5a3969d370cedba388e8eb359d415c33cf2f2265cd5422e4/919966b4-b36b-4bc4-9a46-e817c9e5d3a1: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/2f7dfc55ecf5537d5a3969d370cedba388e8eb359d415c33cf2f2265cd5422e4/919966b4-b36b-4bc4-9a46-e817c9e5d3a1": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/2f7dfc55ecf5537d5a3969d370cedba388e8eb359d415c33cf2f2265cd5422e4/919966b4-b36b-4bc4-9a46-e817c9e5d3a1/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/2f7dfc55ecf5537d5a3969d370cedba388e8eb359d415c33cf2f2265cd5422e4/919966b4-b36b-4bc4-9a46-e817c9e5d3a1 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=pilot:sha256-e6ced4eebe1bf888ee8765390fe46654934af632a95310f14c4c7da65edf31c6.sig_2024-06-15_19:32:34.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig_2024-06-15_19:32:44.json istio/proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig] execution failed: exit status 1
Output: 2024-06-15T19:32:45Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:32:47Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:a16e66a50d9cff5c106522ad1ada00fa9a5fe7ec2c147c060fabe4f494a8df26): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig_2024-06-15_19:32:44.json istio/proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig] execution failed: exit status 1
Output: time="2024-06-15T19:32:47Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:a16e66a50d9cff5c106522ad1ada00fa9a5fe7ec2c147c060fabe4f494a8df26" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=245
time="2024-06-15T19:32:47Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:a16e66a50d9cff5c106522ad1ada00fa9a5fe7ec2c147c060fabe4f494a8df26" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig_2024-06-15_19:32:44.json istio/proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/8fa31da6610173531c4cb6e3a07f4ad623343d82db5a591fe4b1d4c18763bebe/fcc833a0-ef9a-4285-a345-ad41d1d16a84', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/8fa31da6610173531c4cb6e3a07f4ad623343d82db5a591fe4b1d4c18763bebe/fcc833a0-ef9a-4285-a345-ad41d1d16a84: is a directory
read /tmp/docker-scout/sha256/8fa31da6610173531c4cb6e3a07f4ad623343d82db5a591fe4b1d4c18763bebe/fcc833a0-ef9a-4285-a345-ad41d1d16a84: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/8fa31da6610173531c4cb6e3a07f4ad623343d82db5a591fe4b1d4c18763bebe/fcc833a0-ef9a-4285-a345-ad41d1d16a84: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/8fa31da6610173531c4cb6e3a07f4ad623343d82db5a591fe4b1d4c18763bebe/fcc833a0-ef9a-4285-a345-ad41d1d16a84": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/8fa31da6610173531c4cb6e3a07f4ad623343d82db5a591fe4b1d4c18763bebe/fcc833a0-ef9a-4285-a345-ad41d1d16a84/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/8fa31da6610173531c4cb6e3a07f4ad623343d82db5a591fe4b1d4c18763bebe/fcc833a0-ef9a-4285-a345-ad41d1d16a84 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=proxyv2:sha256-f93a26e621330618787829356be8644fb911d4573d89f63298e4ebc84922b7f1.sig_2024-06-15_19:32:44.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig_2024-06-15_19:32:54.json istio/proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig] execution failed: exit status 1
Output: 2024-06-15T19:32:55Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:32:57Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:bb6bd57f1abd7981bc88fd056373f48811e9e3646065ce7f4ebb67c4d41b2dbb): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig_2024-06-15_19:32:54.json istio/proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig] execution failed: exit status 1
Output: time="2024-06-15T19:32:57Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:bb6bd57f1abd7981bc88fd056373f48811e9e3646065ce7f4ebb67c4d41b2dbb" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=245
time="2024-06-15T19:32:57Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:57Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:57Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:32:57Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:bb6bd57f1abd7981bc88fd056373f48811e9e3646065ce7f4ebb67c4d41b2dbb" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig_2024-06-15_19:32:54.json istio/proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/5d95db9f66a1f2c0bb23ee1e34f98988af67243994d83f2ba07a6293f5edbaa4/583b6e23-507d-44bc-aeb8-c0299b86e0b0', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/5d95db9f66a1f2c0bb23ee1e34f98988af67243994d83f2ba07a6293f5edbaa4/583b6e23-507d-44bc-aeb8-c0299b86e0b0: is a directory
read /tmp/docker-scout/sha256/5d95db9f66a1f2c0bb23ee1e34f98988af67243994d83f2ba07a6293f5edbaa4/583b6e23-507d-44bc-aeb8-c0299b86e0b0: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/5d95db9f66a1f2c0bb23ee1e34f98988af67243994d83f2ba07a6293f5edbaa4/583b6e23-507d-44bc-aeb8-c0299b86e0b0: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/5d95db9f66a1f2c0bb23ee1e34f98988af67243994d83f2ba07a6293f5edbaa4/583b6e23-507d-44bc-aeb8-c0299b86e0b0": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/5d95db9f66a1f2c0bb23ee1e34f98988af67243994d83f2ba07a6293f5edbaa4/583b6e23-507d-44bc-aeb8-c0299b86e0b0/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/5d95db9f66a1f2c0bb23ee1e34f98988af67243994d83f2ba07a6293f5edbaa4/583b6e23-507d-44bc-aeb8-c0299b86e0b0 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=proxyv2:sha256-e6b5a980e618feb51144fe2056fb385946f63bbaabe845adb6862b756df9f23c.sig_2024-06-15_19:32:54.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig_2024-06-15_19:33:05.json istio/proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig] execution failed: exit status 1
Output: 2024-06-15T19:33:06Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:33:07Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:d4c32be094fa388a64c1f0c72c1e1a9f98c92d74661633980e5597064b12384c): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig_2024-06-15_19:33:05.json istio/proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig] execution failed: exit status 1
Output: time="2024-06-15T19:33:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:d4c32be094fa388a64c1f0c72c1e1a9f98c92d74661633980e5597064b12384c" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=245
time="2024-06-15T19:33:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:08Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:08Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:d4c32be094fa388a64c1f0c72c1e1a9f98c92d74661633980e5597064b12384c" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig_2024-06-15_19:33:05.json istio/proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/21778b69b3024de4bad7d25ce9fc6a89523162a84c9d36a2c9da04e51a7e9373/3233870a-5c91-4f11-8762-3bdc723c9500', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/21778b69b3024de4bad7d25ce9fc6a89523162a84c9d36a2c9da04e51a7e9373/3233870a-5c91-4f11-8762-3bdc723c9500: is a directory
read /tmp/docker-scout/sha256/21778b69b3024de4bad7d25ce9fc6a89523162a84c9d36a2c9da04e51a7e9373/3233870a-5c91-4f11-8762-3bdc723c9500: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/21778b69b3024de4bad7d25ce9fc6a89523162a84c9d36a2c9da04e51a7e9373/3233870a-5c91-4f11-8762-3bdc723c9500: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/21778b69b3024de4bad7d25ce9fc6a89523162a84c9d36a2c9da04e51a7e9373/3233870a-5c91-4f11-8762-3bdc723c9500": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/21778b69b3024de4bad7d25ce9fc6a89523162a84c9d36a2c9da04e51a7e9373/3233870a-5c91-4f11-8762-3bdc723c9500/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/21778b69b3024de4bad7d25ce9fc6a89523162a84c9d36a2c9da04e51a7e9373/3233870a-5c91-4f11-8762-3bdc723c9500 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=proxyv2:sha256-62ca29ef14b13cdc135e4ca1f66b86ccaafbd604a3f564d58091fe00d753b9dc.sig_2024-06-15_19:33:05.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/proxyv2:1.22.1-distroless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
istio/proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig_2024-06-15_19:33:31.json istio/proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig] execution failed: exit status 1
Output: 2024-06-15T19:33:32Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:33:33Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:c9af7f2b9c35292ea36288b95087f9be2f4937db5b237a427b2a59a2235dd27d): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig_2024-06-15_19:33:31.json istio/proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig] execution failed: exit status 1
Output: time="2024-06-15T19:33:34Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:c9af7f2b9c35292ea36288b95087f9be2f4937db5b237a427b2a59a2235dd27d" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=245
time="2024-06-15T19:33:34Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:33:34Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:c9af7f2b9c35292ea36288b95087f9be2f4937db5b237a427b2a59a2235dd27d" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig_2024-06-15_19:33:31.json istio/proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/9c6d8130e42ba086855ea512ee34413af64b9e8f72fa921a8efc85d9bdc0dd01/8896dc3e-cfbc-4098-8944-e8ae5cfdd7c0', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/9c6d8130e42ba086855ea512ee34413af64b9e8f72fa921a8efc85d9bdc0dd01/8896dc3e-cfbc-4098-8944-e8ae5cfdd7c0: is a directory
read /tmp/docker-scout/sha256/9c6d8130e42ba086855ea512ee34413af64b9e8f72fa921a8efc85d9bdc0dd01/8896dc3e-cfbc-4098-8944-e8ae5cfdd7c0: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/9c6d8130e42ba086855ea512ee34413af64b9e8f72fa921a8efc85d9bdc0dd01/8896dc3e-cfbc-4098-8944-e8ae5cfdd7c0: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/9c6d8130e42ba086855ea512ee34413af64b9e8f72fa921a8efc85d9bdc0dd01/8896dc3e-cfbc-4098-8944-e8ae5cfdd7c0": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/9c6d8130e42ba086855ea512ee34413af64b9e8f72fa921a8efc85d9bdc0dd01/8896dc3e-cfbc-4098-8944-e8ae5cfdd7c0/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/9c6d8130e42ba086855ea512ee34413af64b9e8f72fa921a8efc85d9bdc0dd01/8896dc3e-cfbc-4098-8944-e8ae5cfdd7c0 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=proxyv2:sha256-94caee76052d3ebba6b7d0ed6572379b043b43f715224fb9c6043003e91c9e3b.sig_2024-06-15_19:33:31.json] execution failed: exit status 2
Output: Invalid OCI archive

containrrr/watchtower:latest-dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
containrrr/watchtower:1.7.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
containrrr/watchtower:arm64v8-latest ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test containrrr/watchtower:arm64v8-latest --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_containrrr=watchtower:arm64v8-latest_2024-06-15_19:33:56.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
containrrr/watchtower:arm64v8-1.7.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test containrrr/watchtower:arm64v8-1.7.1 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_containrrr=watchtower:arm64v8-1.7.1_2024-06-15_19:34:03.json] execution failed: exit status 2
Output: Invalid OCI archive

containrrr/watchtower:armhf-latest ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test containrrr/watchtower:armhf-latest --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_containrrr=watchtower:armhf-latest_2024-06-15_19:34:09.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
curlimages/curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_curlimages=curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig_2024-06-15_19:34:16.json curlimages/curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig] execution failed: exit status 1
Output: 2024-06-15T19:34:17Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:34:19Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:d62017957004db9f25e24655209d58e1464949182eb2b697f5382cf903a977d1): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_curlimages=curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig_2024-06-15_19:34:16.json curlimages/curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig] execution failed: exit status 1
Output: time="2024-06-15T19:34:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:d62017957004db9f25e24655209d58e1464949182eb2b697f5382cf903a977d1" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=247
time="2024-06-15T19:34:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:d62017957004db9f25e24655209d58e1464949182eb2b697f5382cf903a977d1" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=247
time="2024-06-15T19:34:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'curlimages/curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: curlimages/curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:d62017957004db9f25e24655209d58e1464949182eb2b697f5382cf903a977d1" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_curlimages=curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig_2024-06-15_19:34:16.json curlimages/curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/3d4c05bf649948b3e862ac28365f54b512e061859fc18bb2ab4f5f979f17674b/76ce2f1d-1a9a-41a4-a118-932768403564', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/3d4c05bf649948b3e862ac28365f54b512e061859fc18bb2ab4f5f979f17674b/76ce2f1d-1a9a-41a4-a118-932768403564: is a directory
read /tmp/docker-scout/sha256/3d4c05bf649948b3e862ac28365f54b512e061859fc18bb2ab4f5f979f17674b/76ce2f1d-1a9a-41a4-a118-932768403564: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/3d4c05bf649948b3e862ac28365f54b512e061859fc18bb2ab4f5f979f17674b/76ce2f1d-1a9a-41a4-a118-932768403564: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/3d4c05bf649948b3e862ac28365f54b512e061859fc18bb2ab4f5f979f17674b/76ce2f1d-1a9a-41a4-a118-932768403564": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/3d4c05bf649948b3e862ac28365f54b512e061859fc18bb2ab4f5f979f17674b/76ce2f1d-1a9a-41a4-a118-932768403564/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/3d4c05bf649948b3e862ac28365f54b512e061859fc18bb2ab4f5f979f17674b/76ce2f1d-1a9a-41a4-a118-932768403564 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test curlimages/curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_curlimages=curl:sha256-73e4d532ea62d7505c5865b517d3704966ffe916609bedc22af6833dc9969bcd.sig_2024-06-15_19:34:16.json] execution failed: exit status 2
Output: Invalid OCI archive

curlimages/curl:8.8.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
curlimages/curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_curlimages=curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig_2024-06-15_19:34:35.json curlimages/curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig] execution failed: exit status 1
Output: 2024-06-15T19:34:36Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:34:38Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:3deeae947e8f82e5d1f325312bb7b4e681e5169667138dd5b99aab1440323701): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_curlimages=curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig_2024-06-15_19:34:35.json curlimages/curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig] execution failed: exit status 1
Output: time="2024-06-15T19:34:37Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:3deeae947e8f82e5d1f325312bb7b4e681e5169667138dd5b99aab1440323701" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=247
time="2024-06-15T19:34:37Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:3deeae947e8f82e5d1f325312bb7b4e681e5169667138dd5b99aab1440323701" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=247
time="2024-06-15T19:34:37Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:37Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:37Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:38Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:38Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:38Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:38Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:38Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:38Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:38Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:38Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'curlimages/curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: curlimages/curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:3deeae947e8f82e5d1f325312bb7b4e681e5169667138dd5b99aab1440323701" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_curlimages=curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig_2024-06-15_19:34:35.json curlimages/curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/98e9cc04f43b2841516b2226d81070687b059813046cdf54ec0651dd86137476/017d2868-e9fc-47e3-8e99-ef204a11c220', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/98e9cc04f43b2841516b2226d81070687b059813046cdf54ec0651dd86137476/017d2868-e9fc-47e3-8e99-ef204a11c220: is a directory
read /tmp/docker-scout/sha256/98e9cc04f43b2841516b2226d81070687b059813046cdf54ec0651dd86137476/017d2868-e9fc-47e3-8e99-ef204a11c220: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/98e9cc04f43b2841516b2226d81070687b059813046cdf54ec0651dd86137476/017d2868-e9fc-47e3-8e99-ef204a11c220: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/98e9cc04f43b2841516b2226d81070687b059813046cdf54ec0651dd86137476/017d2868-e9fc-47e3-8e99-ef204a11c220": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/98e9cc04f43b2841516b2226d81070687b059813046cdf54ec0651dd86137476/017d2868-e9fc-47e3-8e99-ef204a11c220/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/98e9cc04f43b2841516b2226d81070687b059813046cdf54ec0651dd86137476/017d2868-e9fc-47e3-8e99-ef204a11c220 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test curlimages/curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_curlimages=curl:sha256-25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21.sig_2024-06-15_19:34:35.json] execution failed: exit status 2
Output: Invalid OCI archive

curlimages/curl:8.7.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
curlimages/curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_curlimages=curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig_2024-06-15_19:34:53.json curlimages/curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig] execution failed: exit status 1
Output: 2024-06-15T19:34:54Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:34:55Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:6a2f18a67cd2b0c1cf952d69327d79d2db7660029989f27903588f50dd7b570b): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_curlimages=curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig_2024-06-15_19:34:53.json curlimages/curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig] execution failed: exit status 1
Output: time="2024-06-15T19:34:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:6a2f18a67cd2b0c1cf952d69327d79d2db7660029989f27903588f50dd7b570b" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=247
time="2024-06-15T19:34:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:6a2f18a67cd2b0c1cf952d69327d79d2db7660029989f27903588f50dd7b570b" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=247
time="2024-06-15T19:34:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:55Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:34:56Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'curlimages/curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: curlimages/curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:6a2f18a67cd2b0c1cf952d69327d79d2db7660029989f27903588f50dd7b570b" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_curlimages=curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig_2024-06-15_19:34:53.json curlimages/curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/f4a3ae697ef6325103fe21e060de716c19fe2ace03c76ac1aae11202304ca2f4/6665bd4a-d162-4a74-aac9-77878a44e7ca', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/f4a3ae697ef6325103fe21e060de716c19fe2ace03c76ac1aae11202304ca2f4/6665bd4a-d162-4a74-aac9-77878a44e7ca: is a directory
read /tmp/docker-scout/sha256/f4a3ae697ef6325103fe21e060de716c19fe2ace03c76ac1aae11202304ca2f4/6665bd4a-d162-4a74-aac9-77878a44e7ca: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/f4a3ae697ef6325103fe21e060de716c19fe2ace03c76ac1aae11202304ca2f4/6665bd4a-d162-4a74-aac9-77878a44e7ca: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/f4a3ae697ef6325103fe21e060de716c19fe2ace03c76ac1aae11202304ca2f4/6665bd4a-d162-4a74-aac9-77878a44e7ca": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/f4a3ae697ef6325103fe21e060de716c19fe2ace03c76ac1aae11202304ca2f4/6665bd4a-d162-4a74-aac9-77878a44e7ca/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/f4a3ae697ef6325103fe21e060de716c19fe2ace03c76ac1aae11202304ca2f4/6665bd4a-d162-4a74-aac9-77878a44e7ca Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test curlimages/curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_curlimages=curl:sha256-c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b.sig_2024-06-15_19:34:53.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig_2024-06-15_19:35:05.json istio/operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig] execution failed: exit status 1
Output: 2024-06-15T19:35:06Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:35:07Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:fbd166b42176b0f255241de37f68f3e1289b7269378c41d5a6afaa5e1e930cd1): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig_2024-06-15_19:35:05.json istio/operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig] execution failed: exit status 1
Output: time="2024-06-15T19:35:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:fbd166b42176b0f255241de37f68f3e1289b7269378c41d5a6afaa5e1e930cd1" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=246
time="2024-06-15T19:35:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:07Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:08Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:08Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:08Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:08Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:fbd166b42176b0f255241de37f68f3e1289b7269378c41d5a6afaa5e1e930cd1" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig_2024-06-15_19:35:05.json istio/operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/7c34a731e1b0cc34cace91f79670065d214d63633f048f26827f48e3aa6e527b/809f9a14-232a-464a-a24d-c533536cf4fa', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/7c34a731e1b0cc34cace91f79670065d214d63633f048f26827f48e3aa6e527b/809f9a14-232a-464a-a24d-c533536cf4fa: is a directory
read /tmp/docker-scout/sha256/7c34a731e1b0cc34cace91f79670065d214d63633f048f26827f48e3aa6e527b/809f9a14-232a-464a-a24d-c533536cf4fa: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/7c34a731e1b0cc34cace91f79670065d214d63633f048f26827f48e3aa6e527b/809f9a14-232a-464a-a24d-c533536cf4fa: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/7c34a731e1b0cc34cace91f79670065d214d63633f048f26827f48e3aa6e527b/809f9a14-232a-464a-a24d-c533536cf4fa": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/7c34a731e1b0cc34cace91f79670065d214d63633f048f26827f48e3aa6e527b/809f9a14-232a-464a-a24d-c533536cf4fa/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/7c34a731e1b0cc34cace91f79670065d214d63633f048f26827f48e3aa6e527b/809f9a14-232a-464a-a24d-c533536cf4fa Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=operator:sha256-261c1b269a6cb0ba2c7caf77dcb6606d765934a41eb453bdbbb90772edfb818a.sig_2024-06-15_19:35:05.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig_2024-06-15_19:35:15.json istio/operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig] execution failed: exit status 1
Output: 2024-06-15T19:35:16Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:35:18Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:d456c5f276ca90e0fd6877551c704e968cf1ca8c8e82ba3c07cfc8ecafac5716): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig_2024-06-15_19:35:15.json istio/operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig] execution failed: exit status 1
Output: time="2024-06-15T19:35:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:d456c5f276ca90e0fd6877551c704e968cf1ca8c8e82ba3c07cfc8ecafac5716" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=246
time="2024-06-15T19:35:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:18Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:19Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:d456c5f276ca90e0fd6877551c704e968cf1ca8c8e82ba3c07cfc8ecafac5716" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig_2024-06-15_19:35:15.json istio/operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/cc22d936f330c79d6c0a2c0c000fb6976f28d36f42a182711118379ce7a2c67e/224c48ef-4414-49d4-9b92-c0f00d8518d8', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/cc22d936f330c79d6c0a2c0c000fb6976f28d36f42a182711118379ce7a2c67e/224c48ef-4414-49d4-9b92-c0f00d8518d8: is a directory
read /tmp/docker-scout/sha256/cc22d936f330c79d6c0a2c0c000fb6976f28d36f42a182711118379ce7a2c67e/224c48ef-4414-49d4-9b92-c0f00d8518d8: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/cc22d936f330c79d6c0a2c0c000fb6976f28d36f42a182711118379ce7a2c67e/224c48ef-4414-49d4-9b92-c0f00d8518d8: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/cc22d936f330c79d6c0a2c0c000fb6976f28d36f42a182711118379ce7a2c67e/224c48ef-4414-49d4-9b92-c0f00d8518d8": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/cc22d936f330c79d6c0a2c0c000fb6976f28d36f42a182711118379ce7a2c67e/224c48ef-4414-49d4-9b92-c0f00d8518d8/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/cc22d936f330c79d6c0a2c0c000fb6976f28d36f42a182711118379ce7a2c67e/224c48ef-4414-49d4-9b92-c0f00d8518d8 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=operator:sha256-59820416677f5c9378353a7b433037ac1e514004f9cec5c7d6896bf7bdba8874.sig_2024-06-15_19:35:15.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig_2024-06-15_19:35:26.json istio/operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig] execution failed: exit status 1
Output: 2024-06-15T19:35:26Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:35:28Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:99c6e768f0103cbd7583f823226ea8f273f3371db0b6d2d050e8f0174ef45a01): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig_2024-06-15_19:35:26.json istio/operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig] execution failed: exit status 1
Output: time="2024-06-15T19:35:27Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:99c6e768f0103cbd7583f823226ea8f273f3371db0b6d2d050e8f0174ef45a01" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=246
time="2024-06-15T19:35:27Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:28Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:29Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:29Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:29Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:99c6e768f0103cbd7583f823226ea8f273f3371db0b6d2d050e8f0174ef45a01" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig_2024-06-15_19:35:26.json istio/operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/18cc83c4381ef3c58915c027cebca2b8b59d5051e0e154865218e0980422d64a/f3f7ce23-dabd-4041-a961-b75962e5a1e9', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/18cc83c4381ef3c58915c027cebca2b8b59d5051e0e154865218e0980422d64a/f3f7ce23-dabd-4041-a961-b75962e5a1e9: is a directory
read /tmp/docker-scout/sha256/18cc83c4381ef3c58915c027cebca2b8b59d5051e0e154865218e0980422d64a/f3f7ce23-dabd-4041-a961-b75962e5a1e9: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/18cc83c4381ef3c58915c027cebca2b8b59d5051e0e154865218e0980422d64a/f3f7ce23-dabd-4041-a961-b75962e5a1e9: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/18cc83c4381ef3c58915c027cebca2b8b59d5051e0e154865218e0980422d64a/f3f7ce23-dabd-4041-a961-b75962e5a1e9": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/18cc83c4381ef3c58915c027cebca2b8b59d5051e0e154865218e0980422d64a/f3f7ce23-dabd-4041-a961-b75962e5a1e9/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/18cc83c4381ef3c58915c027cebca2b8b59d5051e0e154865218e0980422d64a/f3f7ce23-dabd-4041-a961-b75962e5a1e9 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=operator:sha256-8b8d7250c8289c95e18575fe49cddbd36c8713011e37eac6cbf0626f0ed6ab7a.sig_2024-06-15_19:35:26.json] execution failed: exit status 2
Output: Invalid OCI archive

istio/operator:1.21.3-distroless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
istio/operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_istio=operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig_2024-06-15_19:35:48.json istio/operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig] execution failed: exit status 1
Output: 2024-06-15T19:35:49Z	INFO	Vulnerability scanning is enabled
2024-06-15T19:35:50Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:c4af5e3b27ad6fbb1c6b818f0262643edff36b885f086729edfff227601ac075): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_istio=operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig_2024-06-15_19:35:48.json istio/operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig] execution failed: exit status 1
Output: time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:c4af5e3b27ad6fbb1c6b818f0262643edff36b885f086729edfff227601ac075" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=246
time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:c4af5e3b27ad6fbb1c6b818f0262643edff36b885f086729edfff227601ac075" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=246
time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T19:35:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'istio/operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: istio/operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:c4af5e3b27ad6fbb1c6b818f0262643edff36b885f086729edfff227601ac075" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_istio=operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig_2024-06-15_19:35:48.json istio/operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/5266d5d46b2292ab7937452795ef438539d059f75bc9ebb6a4a9713a8f091bf3/b07b6197-2832-4c00-af5f-7e18148fd881', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/5266d5d46b2292ab7937452795ef438539d059f75bc9ebb6a4a9713a8f091bf3/b07b6197-2832-4c00-af5f-7e18148fd881: is a directory
read /tmp/docker-scout/sha256/5266d5d46b2292ab7937452795ef438539d059f75bc9ebb6a4a9713a8f091bf3/b07b6197-2832-4c00-af5f-7e18148fd881: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/5266d5d46b2292ab7937452795ef438539d059f75bc9ebb6a4a9713a8f091bf3/b07b6197-2832-4c00-af5f-7e18148fd881: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/5266d5d46b2292ab7937452795ef438539d059f75bc9ebb6a4a9713a8f091bf3/b07b6197-2832-4c00-af5f-7e18148fd881": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/5266d5d46b2292ab7937452795ef438539d059f75bc9ebb6a4a9713a8f091bf3/b07b6197-2832-4c00-af5f-7e18148fd881/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/5266d5d46b2292ab7937452795ef438539d059f75bc9ebb6a4a9713a8f091bf3/b07b6197-2832-4c00-af5f-7e18148fd881 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test istio/operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_istio=operator:sha256-7a6430d39ac8d9ee3b3c7863c13799f25e35225bfd59742da45380e50e10a979.sig_2024-06-15_19:35:48.json] execution failed: exit status 2
Output: Invalid OCI archive

envoyproxy/envoy:tools-dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
envoyproxy/envoy:tools-dev-139fc0fb504850e6d16d7d5e5838956f76a1b27b ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
envoyproxy/envoy:google-vrp-dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
envoyproxy/envoy:google-vrp-dev-139fc0fb504850e6d16d7d5e5838956f76a1b27b ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
envoyproxy/envoy:distroless-dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
jenkins/jenkins:jdk17 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
jenkins/jenkins:latest-jdk17 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
jenkins/jenkins:jdk11 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
jenkins/jenkins:jdk21 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
jenkins/jenkins:latest-jdk11 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
openpolicyagent/gatekeeper:dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
openpolicyagent/gatekeeper:0736dc0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
openpolicyagent/gatekeeper:v3.16.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
openpolicyagent/gatekeeper:ead20a7 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
openpolicyagent/gatekeeper:v3.16.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/radarr:5.7.0-nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/radarr:nightly-version-5.7.0.8862 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/radarr:nightly-5.7.0.8862-ls2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/radarr:nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/radarr:arm64v8-5.7.0-nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/radarr:arm64v8-5.7.0-nightly --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=radarr:arm64v8-5.7.0-nightly_2024-06-15_19:42:55.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/sonarr:4.0.5-develop ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/sonarr:develop-version-4.0.5.1719 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/sonarr:develop-4.0.5.1719-ls64 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/sonarr:develop ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/sonarr:arm64v8-4.0.5-develop ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/sonarr:arm64v8-4.0.5-develop --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=sonarr:arm64v8-4.0.5-develop_2024-06-15_19:44:17.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
fluxcd/flux:1.25.4 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluxcd/flux:1.25.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluxcd/flux:1.25.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluxcd/flux:1.25.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluxcd/flux:1.25.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/jackett:0.22.71 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/jackett:version-v0.22.71 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/jackett:v0.22.71-ls425 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/jackett:arm64v8-0.22.71 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/jackett:arm64v8-0.22.71 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=jackett:arm64v8-0.22.71_2024-06-15_19:47:03.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/jackett:amd64-0.22.71 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
apache/airflow:slim-2.9.2rc1-python3.9 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
apache/airflow:slim-2.9.2rc1-python3.11 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
apache/airflow:slim-2.9.2rc1-python3.8 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
apache/airflow:2.9.2rc1-python3.9 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
apache/airflow:slim-2.9.2rc1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
fluxcd/helm-operator:1.4.4 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluxcd/helm-operator:1.4.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluxcd/helm-operator:1.4.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluxcd/helm-operator:1.4.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
fluxcd/helm-operator:1.4.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/tautulli:develop-version-a3af8ed3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/tautulli:develop-a3af8ed3-ls360 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/tautulli:develop ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/tautulli:arm64v8-develop-version-a3af8ed3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/tautulli:arm64v8-develop-version-a3af8ed3 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=tautulli:arm64v8-develop-version-a3af8ed3_2024-06-15_19:54:17.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/tautulli:arm64v8-develop ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/tautulli:arm64v8-develop --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=tautulli:arm64v8-develop_2024-06-15_19:54:37.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/ombi:4.43.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/ombi:version-v4.43.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/ombi:v4.43.5-ls192 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/ombi:arm64v8-4.43.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/ombi:arm64v8-4.43.5 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=ombi:arm64v8-4.43.5_2024-06-15_19:56:06.json] execution failed: exit status 2
Output: Invalid OCI archive

linuxserver/ombi:amd64-4.43.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
fluent/fluentd-kubernetes-daemonset:v1.16-debian-kafka-2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
fluent/fluentd-kubernetes-daemonset:v1.16.5-debian-kafka-1.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
fluent/fluentd-kubernetes-daemonset:v1.16-debian-kafka-arm64-2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test fluent/fluentd-kubernetes-daemonset:v1.16-debian-kafka-arm64-2 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_fluent=fluentd-kubernetes-daemonset:v1.16-debian-kafka-arm64-2_2024-06-15_19:57:46.json] execution failed: exit status 2
Output: Invalid OCI archive

fluent/fluentd-kubernetes-daemonset:v1.16.5-debian-kafka-arm64-1.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test fluent/fluentd-kubernetes-daemonset:v1.16.5-debian-kafka-arm64-1.0 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_fluent=fluentd-kubernetes-daemonset:v1.16.5-debian-kafka-arm64-1.0_2024-06-15_19:58:15.json] execution failed: exit status 2
Output: Invalid OCI archive

fluent/fluentd-kubernetes-daemonset:v1-debian-kafka-arm64 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test fluent/fluentd-kubernetes-daemonset:v1-debian-kafka-arm64 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_fluent=fluentd-kubernetes-daemonset:v1-debian-kafka-arm64_2024-06-15_19:58:41.json] execution failed: exit status 2
Output: Invalid OCI archive

linuxserver/plex:1.40.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/plex:version-1.40.2.8395-c67dce28e ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/plex:1.40.2.8395-c67dce28e-ls217 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/plex:arm64v8-1.40.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/plex:arm64v8-1.40.2 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=plex:arm64v8-1.40.2_2024-06-15_20:00:24.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/plex:amd64-1.40.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
pihole/pihole:development-v6 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
pihole/pihole:nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
pihole/pihole:dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
pihole/pihole:2024.05.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
pihole/pihole:2024.03.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/nzbget:testing-version-a98e6d1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/nzbget:testing-a98e6d1-ls95 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/nzbget:testing ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/nzbget:arm64v8-testing-version-a98e6d1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/nzbget:arm64v8-testing-version-a98e6d1 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=nzbget:arm64v8-testing-version-a98e6d1_2024-06-15_20:03:43.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/nzbget:arm64v8-testing ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/nzbget:arm64v8-testing --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=nzbget:arm64v8-testing_2024-06-15_20:03:58.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/sabnzbd:nightly-version-2a02c93e ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/sabnzbd:nightly-2a02c93e-ls30 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/sabnzbd:nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/sabnzbd:arm64v8-nightly-version-2a02c93e ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/sabnzbd:arm64v8-nightly-version-2a02c93e --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=sabnzbd:arm64v8-nightly-version-2a02c93e_2024-06-15_20:05:08.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/sabnzbd:arm64v8-nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/sabnzbd:arm64v8-nightly --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=sabnzbd:arm64v8-nightly_2024-06-15_20:05:27.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
homeassistant/home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /root/docker-vulnerability-analyzer/out/sponsored/new1/Trivy_scan_homeassistant=home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig_2024-06-15_20:05:46.json homeassistant/home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig] execution failed: exit status 1
Output: 2024-06-15T20:05:47Z	INFO	Vulnerability scanning is enabled
2024-06-15T20:05:49Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:bf985166dbc64c4cc753e78defe06e681b7726e460a4da2cfde4e62a092004d3): walk error: failed to extract the archive: unexpected EOF
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /root/docker-vulnerability-analyzer/out/sponsored/new1/Grype_scan_homeassistant=home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig_2024-06-15_20:05:46.json homeassistant/home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig] execution failed: exit status 1
Output: time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:bf985166dbc64c4cc753e78defe06e681b7726e460a4da2cfde4e62a092004d3" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=260
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:bf985166dbc64c4cc753e78defe06e681b7726e460a4da2cfde4e62a092004d3" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=260
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:bf985166dbc64c4cc753e78defe06e681b7726e460a4da2cfde4e62a092004d3" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=260
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:bf985166dbc64c4cc753e78defe06e681b7726e460a4da2cfde4e62a092004d3" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=260
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:bf985166dbc64c4cc753e78defe06e681b7726e460a4da2cfde4e62a092004d3" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=260
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json" digest="sha256:bf985166dbc64c4cc753e78defe06e681b7726e460a4da2cfde4e62a092004d3" mediatype=application/vnd.dev.cosign.simplesigning.v1+json size=260
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:48Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:49Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:50Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
time="2024-06-15T20:05:51Z" level=warning msg="reference for unknown type: application/vnd.dev.cosign.simplesigning.v1+json"
[31mfailed to catalog: errors occurred attempting to resolve 'homeassistant/home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig':
  - docker: unable to inspect existing image: Error response from daemon: No such image: homeassistant/home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig
  - podman: podman not available: no host address
  - containerd: failed to read layer="sha256:bf985166dbc64c4cc753e78defe06e681b7726e460a4da2cfde4e62a092004d3" tar : unexpected EOF
  - oci-registry: unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
  - additionally, the following providers failed with file does not exist: docker-archive, oci-archive, oci-dir, singularity, oci-dir, local-file, local-directory[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /root/docker-vulnerability-analyzer/out/sponsored/new1/DockerScout_scan_homeassistant=home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig_2024-06-15_20:05:46.json homeassistant/home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig] execution failed: exit status 1
Output:     ...Pulling
    âœ“ Pulled
    ...Storing image for indexing
[31mERROR  [0m Status: failed to copy image: failed to create new image source: unable to detect input for '/tmp/docker-scout/sha256/bac87c6eff7714d00a39e8193231a5a9ceb0f6ce40ccd78100220658b55b1e37/4eeb8514-1e75-43f2-a699-5401b68bc130', errs: unable to provide image from tarball: read /tmp/docker-scout/sha256/bac87c6eff7714d00a39e8193231a5a9ceb0f6ce40ccd78100220658b55b1e37/4eeb8514-1e75-43f2-a699-5401b68bc130: is a directory
read /tmp/docker-scout/sha256/bac87c6eff7714d00a39e8193231a5a9ceb0f6ce40ccd78100220658b55b1e37/4eeb8514-1e75-43f2-a699-5401b68bc130: is a directory
unknown layer media type: application/vnd.dev.cosign.simplesigning.v1+json
failed to load image: reading global header: read /tmp/docker-scout/sha256/bac87c6eff7714d00a39e8193231a5a9ceb0f6ce40ccd78100220658b55b1e37/4eeb8514-1e75-43f2-a699-5401b68bc130: is a directory
pull failed: invalid reference format
podman not available: no host address
pull failed: failed to resolve reference "docker.io//tmp/docker-scout/sha256/bac87c6eff7714d00a39e8193231a5a9ceb0f6ce40ccd78100220658b55b1e37/4eeb8514-1e75-43f2-a699-5401b68bc130": object required
failed to get image descriptor from registry: GET https://index.docker.io/v2/tmp/docker-scout/sha256/bac87c6eff7714d00a39e8193231a5a9ceb0f6ce40ccd78100220658b55b1e37/4eeb8514-1e75-43f2-a699-5401b68bc130/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tmp/docker-scout/sha256/bac87c6eff7714d00a39e8193231a5a9ceb0f6ce40ccd78100220658b55b1e37/4eeb8514-1e75-43f2-a699-5401b68bc130 Type:repository]], Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test homeassistant/home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_homeassistant=home-assistant:sha256-0c2a3f04bdac8f4658ae42fdc83464f77f9f3c87b67bfea608cfa0356e6ed5b0.sig_2024-06-15_20:05:46.json] execution failed: exit status 2
Output: Invalid OCI archive

homeassistant/home-assistant:2024.6 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
homeassistant/home-assistant:rc ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
homeassistant/home-assistant:beta ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
homeassistant/home-assistant:stable ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/heimdall:development-version-f405cf2d ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/heimdall:development-f405cf2d-ls304 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/heimdall:development ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/heimdall:2.6.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/heimdall:version-v2.6.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
openpolicyagent/opa:edge-static-debug ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
openpolicyagent/opa:edge-static ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
openpolicyagent/opa:edge-debug ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
openpolicyagent/opa:edge ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
openpolicyagent/opa:0.66.0-dev-static-debug ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/lidarr:2.4.0-nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/lidarr:nightly-version-2.4.0.4212 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/lidarr:nightly-2.4.0.4212-ls147 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/lidarr:nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/lidarr:arm64v8-2.4.0-nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/lidarr:arm64v8-2.4.0-nightly --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=lidarr:arm64v8-2.4.0-nightly_2024-06-15_20:20:46.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/transmission:4.0.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/transmission:version-4.0.5-r2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/transmission:4.0.5-r2-ls238 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/transmission:arm64v8-4.0.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/transmission:arm64v8-4.0.5 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=transmission:arm64v8-4.0.5_2024-06-15_20:21:43.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/transmission:amd64-4.0.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
apache/superset:066f6b1-websocket ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
apache/superset:066f6b1f8a0eeb10160439da29c1853c3dbe1a8b-websocket ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
apache/superset:066f6b1-dockerize ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
apache/superset:066f6b1f8a0eeb10160439da29c1853c3dbe1a8b-dockerize ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
apache/superset:961cb96-dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/bazarr:1.4.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/bazarr:version-v1.4.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/bazarr:v1.4.3-ls254 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/bazarr:arm64v8-1.4.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/bazarr:arm64v8-1.4.3 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=bazarr:arm64v8-1.4.3_2024-06-15_20:27:03.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/bazarr:amd64-1.4.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
selenium/standalone-chrome:nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/standalone-chrome:dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/standalone-chrome:beta ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/standalone-chrome:125.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/standalone-chrome:125.0-20240522 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
moby/buildkit:master-rootless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
moby/buildkit:master ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
moby/buildkit:nightly-rootless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
moby/buildkit:nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
moby/buildkit:v0.14.0-rc1-rootless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/mariadb:10.11.8 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/mariadb:version-10.11.8-r0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/mariadb:10.11.8-r0-ls144 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/mariadb:arm64v8-10.11.8 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/mariadb:arm64v8-10.11.8 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=mariadb:arm64v8-10.11.8_2024-06-15_20:36:03.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/mariadb:amd64-10.11.8 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/letsencrypt:version-1.11.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/letsencrypt:1.11.0-ls157 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/letsencrypt:arm64v8-version-1.11.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/letsencrypt:arm64v8-version-1.11.0 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=letsencrypt:arm64v8-version-1.11.0_2024-06-15_20:37:34.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/letsencrypt:arm32v7-version-1.11.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/letsencrypt:arm32v7-version-1.11.0 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=letsencrypt:arm32v7-version-1.11.0_2024-06-15_20:37:57.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/letsencrypt:amd64-version-1.11.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
itzg/minecraft-server:java8-graalvm-ce ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
itzg/minecraft-server:java17-graalvm ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
itzg/minecraft-server:java21-graalvm ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
itzg/minecraft-server:java11 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
itzg/minecraft-server:java8-multiarch ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/hydra2:version-v3.0.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/hydra2:v3.0.0-ls19 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/hydra2:dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/hydra2:amd64-version-v3.0.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/hydra2:amd64-dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/unifi-controller:8.0.24 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/unifi-controller:version-8.0.24 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/unifi-controller:8.0.24-ls221 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/unifi-controller:arm64v8-8.0.24 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/unifi-controller:arm64v8-8.0.24 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=unifi-controller:arm64v8-8.0.24_2024-06-15_20:51:42.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/unifi-controller:amd64-8.0.24 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
jenkins/inbound-agent:3248.v65ecb_254c298-5-jdk11-windowsservercore-ltsc2019 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test jenkins/inbound-agent:3248.v65ecb_254c298-5-jdk11-windowsservercore-ltsc2019 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_jenkins=inbound-agent:3248.v65ecb_254c298-5-jdk11-windowsservercore-ltsc2019_2024-06-15_20:53:20.json] execution failed: exit status 2
Output: Operating system is not supported
 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
jenkins/inbound-agent:jdk11-windowsservercore-ltsc2019 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test jenkins/inbound-agent:jdk11-windowsservercore-ltsc2019 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_jenkins=inbound-agent:jdk11-windowsservercore-ltsc2019_2024-06-15_20:58:19.json] execution failed: exit status 2
Output: Operating system is not supported
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
jenkins/inbound-agent:3248.v65ecb_254c298-5-windowsservercore-ltsc2019 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test jenkins/inbound-agent:3248.v65ecb_254c298-5-windowsservercore-ltsc2019 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_jenkins=inbound-agent:3248.v65ecb_254c298-5-windowsservercore-ltsc2019_2024-06-15_21:02:42.json] execution failed: exit status 2
Output: Operating system is not supported
 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
jenkins/inbound-agent:jdk17-windowsservercore-ltsc2019 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test jenkins/inbound-agent:jdk17-windowsservercore-ltsc2019 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_jenkins=inbound-agent:jdk17-windowsservercore-ltsc2019_2024-06-15_21:07:52.json] execution failed: exit status 2
Output: Operating system is not supported
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
jenkins/inbound-agent:3248.v65ecb_254c298-5-jdk17-windowsservercore-ltsc2019 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test jenkins/inbound-agent:3248.v65ecb_254c298-5-jdk17-windowsservercore-ltsc2019 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_jenkins=inbound-agent:3248.v65ecb_254c298-5-jdk17-windowsservercore-ltsc2019_2024-06-15_21:12:02.json] execution failed: exit status 2
Output: Operating system is not supported
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/deluge:2.1.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/deluge:version-2.1.1-r10 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/deluge:2.1.1-r10-ls272 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/deluge:arm64v8-2.1.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/deluge:arm64v8-2.1.1 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=deluge:arm64v8-2.1.1_2024-06-15_21:17:09.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/deluge:amd64-2.1.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/nextcloud:29.0.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/nextcloud:version-29.0.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/nextcloud:29.0.2-ls323 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/nextcloud:arm64v8-29.0.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/nextcloud:arm64v8-29.0.2 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=nextcloud:arm64v8-29.0.2_2024-06-15_21:20:46.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
linuxserver/nextcloud:amd64-29.0.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/qbittorrent:4.6.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/qbittorrent:version-4.6.5-r0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/qbittorrent:4.6.5-r0-ls333 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/qbittorrent:arm64v8-4.6.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/qbittorrent:arm64v8-4.6.5 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=qbittorrent:arm64v8-4.6.5_2024-06-15_21:23:17.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/qbittorrent:amd64-4.6.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
certbot/certbot:v2.11.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
certbot/certbot:arm64v8-latest ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test certbot/certbot:arm64v8-latest --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_certbot=certbot:arm64v8-latest_2024-06-15_21:23:55.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
certbot/certbot:arm64v8-v2.11.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test certbot/certbot:arm64v8-v2.11.0 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_certbot=certbot:arm64v8-v2.11.0_2024-06-15_21:24:09.json] execution failed: exit status 2
Output: Invalid OCI archive

certbot/certbot:amd64-latest ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
certbot/certbot:amd64-v2.11.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
coredns/coredns:1.11.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
coredns/coredns:1.11.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
coredns/coredns:1.10.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
coredns/coredns:1.10.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
coredns/coredns:1.9.4 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
istio/mixer:1.7.8 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
istio/mixer:1.7.8-distroless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
istio/mixer:1.7.7 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
istio/mixer:1.7.7-distroless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
istio/mixer:1.7.6 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
nodered/node-red:3.1-debian ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
nodered/node-red:3.1.9-debian ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
nodered/node-red:latest-debian ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
nodered/node-red:latest-16 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
nodered/node-red:latest-18 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
testcontainers/ryuk:sha-2c469e6792c69398966a96e9bb818436efa15c88 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
testcontainers/ryuk:sha-2c469e6792c69398966a96e9bb818436efa15c88-linux ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
testcontainers/ryuk:sha-2c469e6792c69398966a96e9bb818436efa15c88-windows.ltsc2019 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test testcontainers/ryuk:sha-2c469e6792c69398966a96e9bb818436efa15c88-windows.ltsc2019 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_testcontainers=ryuk:sha-2c469e6792c69398966a96e9bb818436efa15c88-windows.ltsc2019_2024-06-15_21:30:24.json] execution failed: exit status 2
Output: Operating system is not supported
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
testcontainers/ryuk:sha-2c469e6792c69398966a96e9bb818436efa15c88-windows.ltsc2022 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test testcontainers/ryuk:sha-2c469e6792c69398966a96e9bb818436efa15c88-windows.ltsc2022 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_testcontainers=ryuk:sha-2c469e6792c69398966a96e9bb818436efa15c88-windows.ltsc2022_2024-06-15_21:30:47.json] execution failed: exit status 2
Output: Operating system is not supported
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
testcontainers/ryuk:sha-36c16815f2eea54d3336eff6accad9afdb9d86f7 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/node-chrome:nightly ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/node-chrome:dev ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/node-chrome:beta ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/node-chrome:125.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
selenium/node-chrome:125.0-20240522 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
jellyfin/jellyfin:10 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
jellyfin/jellyfin:10.9 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
jellyfin/jellyfin:10.9.6 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
jellyfin/jellyfin:10.9.6.20240606-184155 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
jellyfin/jellyfin:10.9.6-armhf.20240606-184155 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test jellyfin/jellyfin:10.9.6-armhf.20240606-184155 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_jellyfin=jellyfin:10.9.6-armhf.20240606-184155_2024-06-15_21:39:07.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/lazylibrarian:version-d8b2234c ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/lazylibrarian:d8b2234c-ls59 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
linuxserver/lazylibrarian:arm64v8-version-d8b2234c ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/lazylibrarian:arm64v8-version-d8b2234c --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=lazylibrarian:arm64v8-version-d8b2234c_2024-06-15_21:40:28.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/lazylibrarian:arm64v8-latest ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/lazylibrarian:arm64v8-latest --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=lazylibrarian:arm64v8-latest_2024-06-15_21:40:55.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
linuxserver/lazylibrarian:arm64v8-d8b2234c-ls59 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test linuxserver/lazylibrarian:arm64v8-d8b2234c-ls59 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_linuxserver=lazylibrarian:arm64v8-d8b2234c-ls59_2024-06-15_21:41:23.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
localstack/localstack:latest-arm64 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test localstack/localstack:latest-arm64 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_localstack=localstack:latest-arm64_2024-06-15_21:41:50.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
localstack/localstack:latest-amd64 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil>
localstack/localstack:s3-latest ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
localstack/localstack:s3-latest-arm64 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test localstack/localstack:s3-latest-arm64 --sarif-file-output=/root/docker-vulnerability-analyzer/out/sponsored/new1/Snyk_scan_localstack=localstack:s3-latest-arm64_2024-06-15_21:44:44.json] execution failed: exit status 2
Output: Invalid OCI archive
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
localstack/localstack:s3-latest-amd64 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
verdaccio/verdaccio:5.x-next ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
verdaccio/verdaccio:5.31 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
verdaccio/verdaccio:5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
verdaccio/verdaccio:5.31.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
